<?php
/**
 * Customizer default values.
 *
 * @package OneStore
 **/

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$colors                                               = OneStore_Customizer::instance()->get_default_colors();

$predefined                                           = array();

$predefined = array(
	'wc_single_layout_items_top' => array(),
	'wc_single_layout_items_main_left' => array( 0 => 'gallery' ),
	'wc_single_layout_items_main_right' => array(
		0 => 'title',
		1 => 'rating',
		2 => 'price',
		3 => 'excerpt',
		4 => 'form',
		5 => 'meta',
	),
	'wc_single_layout_items_bottom' => array(
		0 => 'data_sections',
		1 => 'related',
	),
	'wc_single_row_gap' => '35px',
	'wc_single_main_left_padding' => '0px 0px 0px 0px',
	'wc_single_main_left_margin' => '0em 0em 0em 0em',
	'wc_single_main_left_width' => '50%',
	'wc_single_main_left_margin__tablet' => '0em 0em 0em 0em',
	'wc_single_main_left_margin__mobile' => '-1em auto 2em auto',
	'wc_single_main_left_width__mobile' => '100%',
	'wc_single_main_right_padding' => '0em 0em 0em 2em',
	'wc_single_main_right_width' => '40%',
	'wc_single_main_right_width__tablet' => '48%',
	'wc_single_main_right_padding__mobile' => '0 0 2em 0',
	'wc_single_main_right_width__mobile' => '100%',
	'woocommerce_single_gallery_zoom' => 1,
	'woocommerce_single_gallery_lightbox' => 1,
	'woocommerce_single_buy_now' => 1,
	'woocommerce_single_wishlist' => 1,
	'woocommerce_single_more_grid_columns' => '4-3-2',
	'woocommerce_single_more_posts_per_page' => '4',
	'woocommerce_single_sticky_cart' => 'bottom',
	'body_font_family' => 'google_fonts|Poppins',
	'body_font_weight' => '400',
	'body_font_style' => 'normal',
	'body_font_size' => '14px',
	'body_line_height' => '1.8',
	'body_letter_spacing' => '0px',
	'body_background_color' => '#f5f5f5',
	'font_smoothing' => 1,
	'h1_font_family' => 'google_fonts|PT Sans',
	'h1_font_weight' => '700',
	'h1_font_style' => '',
	'h1_text_transform' => 'capitalize',
	'h1_letter_spacing' => '0.6px',
	'h2_letter_spacing' => '0.6px',
	'h3_letter_spacing' => '0.6px',
	'h4_letter_spacing' => '0.6px',
	'button_padding' => '',
	'button_font_size' => '0.8em',
	'input_padding' => '',
	'input_border_color' => '',
	'meta_font_family' => '',
	'meta_font_style' => 'italic',
	'page_layout' => 'full-width',
	'boxed_page_padding' => '',
	'boxed_page_margin' => '',
	'boxed_page_background_color' => '#e0e0e0',
	'boxed_page_width' => '1170px',
	'boxed_page_min_width' => '',
	'boxed_page_inner_padding' => '0em 4em 0em 4em',
	'boxed_page_inner_padding__tablet' => '0em 2em 0em 2em',
	'boxed_page_inner_padding__mobile' => '0em 1em 0em 1em',
	'full_width_section_padding' => '0em 4em 0em 4em',
	'full_width_section_margin' => '',
	'full_width_section_max_width' => '1170px',
	'full_width_section_padding__tablet' => '0em 2em 0em 2em',
	'full_width_section_padding__mobile' => '0em 1em 0em 1em',
	'content_layout' => 'right-sidebar',
	'content_main_padding' => '',
	'content_main_margin' => '0px auto 0px auto',
	'content_main_background_color' => '',
	'content_main_max_width' => '',
	'content_main_padding__tablet' => '0em 0em 0em 0em',
	'content_main_margin__tablet' => '0em auto 0em auto',
	'content_main_padding__mobile' => '1em 0em 1em 0em',
	'content_main_margin__mobile' => '0em 0em 0em 0em',
	'content_area_padding' => '3em 0 3em 0',
	'content_area_padding__tablet' => '2em 0 2em 0',
	'content_area_padding__mobile' => '1px 0 1px 0',
	'sidebar_padding' => '3em 0em 3em 0em',
	'sidebar_background_color' => '',
	'sidebar_widget_background_color_heading' => '',
	'sidebar_content_gap' => '3em',
	'sidebar_content_gap__tablet' => '0px',
	'sidebar_content_gap__mobile' => '0px',
	'header_top_bar_merged' => 0,
	'header_top_bar_container' => 'default',
	'header_top_bar_padding' => '',
	'header_top_bar_font_size' => '12px',
	'header_top_bar_color' => '#ffffff',
	'header_top_bar_background_color' => '#4f4f4f',
	'header_top_bar_border_color' => 'rgba(0,0,0,0.1)',
	'header_top_bar_height' => '',
	'header_main_bar_container' => 'default',
	'header_main_bar_sticky' => 0,
	'header_main_bar_items_gutter' => '15px',
	'header_main_bar_icon_size' => '25px',
	'header_main_bar_padding' => '',
	'header_main_bar_background_color' => '',
	'header_main_bar_border_width' => '0px 0px 1px 0px',
	'header_main_bar_border_color' => '',
	'header_main_bar_border_style' => 'solid',
	'header_main_bar_height' => '75px',
	'header_main_bar_link_padding' => '',
	'header_main_bar_link_text_transform' => 'uppercase',
	'header_main_bar_link_color' => '',
	'header_main_bar_link_border_width' => '',
	'header_main_bar_link_border_color' => '',
	'header_main_bar_link_border_style' => '',
	'header_main_bar_submenu_background_color' => '#f5f5f5',
	'header_main_bar_submenu_border_width' => '2px 0 0 0',
	'header_main_bar_submenu_border_color' => '#333333',
	'header_main_bar_submenu_width' => '200px',
	'header_main_bar_submenu_background_color_item' => '',
	'header_main_bar_submenu_background_color_hover' => '#ededed',
	'header_mobile_main_bar_sticky' => 0,
	'header_mobile_main_bar_items_gutter' => '5px',
	'header_mobile_main_bar_icon_size' => '20px',
	'header_mobile_main_padding' => '',
	'header_mobile_main_font_size' => '',
	'header_mobile_main_color' => '',
	'header_mobile_main_background_color' => '',
	'header_mobile_vertical_bar_position' => 'left',
	'header_mobile_vertical_bar_items_gutter' => '',
	'header_mobile_vertical_bar_icon_size' => '33px',
	'page_header' => 1,
	'page_header_elements_left' => array(
		0 => 'title',
		1 => 'breadcrumb',
	),
	'page_header_elements_center' => array(),
	'page_header_elements_right' => array(),
	'page_header_wrapper_padding' => '',
	'page_header_wrapper_background_image' => '',
	'page_header_wrapper_background_color' => '',
	'page_header_wrapper_background_position' => 'center',
	'page_header_wrapper_background_size' => 'cover',
	'page_header_wrapper_border_width' => '0 0 1px 0',
	'page_header_wrapper_max_width' => '',
	'page_header_wrapper_height' => '120px',
	'page_header_wrapper_height__tablet' => '154px',
	'page_header_wrapper_align_items__tablet' => '',
	'page_header_overlay_background_color' => '',
	'canvas_side_width' => '360px',
	'footer_widgets_bar_meta_border_color' => 'rgba(255,255,255,0.21)',
	'footer_bottom_padding' => '5em 4em 5em 4em',
	'footer_bottom_background_color' => '#282828',
	'footer_bottom_padding__tablet' => '2em 2em 2em 2em',
	'footer_bottom_padding__mobile' => '3em 1em 3em 1em',
	'footer_bottom_widgets_color' => '#d1d1d1',
	'footer_bottom_widgets_color_heading' => '#d1d1d1',
	'footer_bottom_widget_link_color' => '#d1d1d1',
	'footer_bottom_bar_padding' => '2em 4em 2em 4em',
	'woocommerce_single_tabs_display' => 'modal',
	'woocommerce_single_readmore' => 1,
	'savp_border_width' => '1px',
	'savp_archive_swatch_size' => '20px',
	'savp_single_canvas' => 'right',
	'savp_border_width_singular' => '1px',
	'savp_archive_swatch_size_single' => '30px',
	'savp_archive_swatch_size_image_single' => '60px',
	'savp_gallery_type' => 'slider',
	'savp_gallery_nav_pos' => 'left',
	'savp_gallery_nav_size' => '85px',
	'savp_gallery_spacing' => '15px',
	'header_elements_top_left' => array(
		0 => 'html-1',
		1 => 'button-2',
		2 => 'button-1',
	),
	'header_elements_top_center' => array(),
	'header_elements_top_right' => array( 0 => 'social' ),
	'header_elements_main_left' => array(
		0 => 'mobile-vertical-toggle',
		1 => 'logo',
		2 => 'menu-1',
	),
	'header_elements_main_center' => array(),
	'header_elements_main_right' => array(
		0 => 'hotline',
		1 => 'search-dropdown',
		2 => 'shopping-cart',
		3 => 'account',
	),
	'header_elements_bottom_left' => array(),
	'header_elements_bottom_center' => array(),
	'header_elements_bottom_right' => array(),
	'header_mobile_elements_top_left' => array(),
	'header_mobile_elements_main_left' => array(
		0 => 'mobile-vertical-toggle',
		1 => 'search-dropdown',
	),
	'header_mobile_elements_main_center' => array( 0 => 'mobile-logo' ),
	'header_mobile_elements_main_right' => array(
		0 => 'shopping-cart',
		1 => 'account',
	),
	'header_mobile_elements_vertical_top' => array(
		0 => 'mobile-menu',
		1 => 'hotline',
		2 => 'html-1',
		3 => 'html-2',
	),
	'header_logo_width' => '125px',
	'header_mobile_logo_width' => '100px',
	'header_html_1_content' => 'Add anything here or just remove it....',
	'header_html_2_content' => 'Html 2 herre',
	'header_html_3_content' => 'HTMl 3 herre',
	'header_button_1_text' => '+88 123 666 888',
	'header_button_1_url' => '#',
	'header_button_1_icon' => ':phone',
	'header_button_1_class' => 'link-only',
	'header_button_2_text' => 'Can we help you?',
	'header_button_2_url' => '#',
	'header_button_2_icon' => ':info',
	'header_button_2_class' => 'link-only',
	'header_search_bar_width' => '500px',
	'heading_header_search_product_only' => 1,
	'heading_header_search_product_cat' => 1,
	'header_social_links' => array(
		0 => 'facebook',
		1 => 'twitter',
		2 => 'instagram',
		3 => 'google-plus',
		4 => 'youtube',
	),
	'footer_widgets_bar' => '4',
	'footer_elements_bottom_left' => array( 0 => 'copyright' ),
	'footer_elements_bottom_center' => array(),
	'footer_elements_bottom_right' => array( 0 => 'menu-1' ),
	'footer_copyright_content' => 'Copyright © {{year}} {{sitename}}',
	'scroll_to_top' => 1,
	'scroll_to_top_icon_size' => '29px',
	'scroll_to_top_padding' => '3px',
	'scroll_to_top_border_radius' => '10px',
	'color_palette_in_gutenberg' => 1,
	'google_fonts_subsets' => array( 0 => 'latin-ext' ),
	'social_behance' => '#',
	'social_dribbble' => '#',
	'social_facebook' => '#',
	'social_github' => '#',
	'social_google-plus' => '#',
	'social_instagram' => '#',
	'social_linkedin' => '#',
	'social_medium' => '#',
	'social_pinterest' => '#',
	'social_rss' => '#',
	'social_twitter' => '#',
	'social_vimeo' => '#',
	'social_vk' => '#',
	'social_youtube' => '#',
	'blog_index_columns' => '2',
	'blog_index_thumb_size' => '80%',
	'blog_index_cols_gutter' => '1em',
	'blog_index_rows_gutter' => '1em',
	'post_index_meta_elements' => array(
		0 => 'author',
		1 => 'categories',
		2 => 'date',
	),
	'post_index_excerpt_length' => '20',
	'woocommerce_index_item_elements_top' => array(),
	'woocommerce_index_item_elements_thumb_left' => array( 0 => 'wc_sale' ),
	'woocommerce_index_item_elements_thumb_right' => array( 0 => 'wc_sale_percent' ),
	'woocommerce_index_item_elements_thumb_bottom' => array(
		0 => 'wc_add_to_cart_icon',
		1 => 'wc_wishlist_icon',
		2 => 'wc_quick_view_icon',
	),
	'woocommerce_index_item_elements_body_left' => array(
		0 => 'wc_title',
		1 => 'wc_swatches',
	),
	'woocommerce_index_item_elements_body' => array(),
	'woocommerce_index_item_elements_body_right' => array( 0 => 'wc_price_less' ),
	'woocommerce_index_item_elements_bottom_left' => array( 0 => 'wc_category' ),
	'woocommerce_index_item_elements_bottom' => array(),
	'woocommerce_index_item_elements_bottom_right' => array(),
	'posts_index_item_elements_top' => array(),
	'posts_index_item_elements_thumb_bottom' => array(),
	'posts_index_item_elements_body_before' => array( 0 => 'post_title' ),
	'posts_index_item_elements_body_left' => array(),
	'posts_index_item_elements_body' => array( 0 => 'post_excerpt' ),
	'posts_index_item_elements_body_right' => array(),
	'posts_index_item_elements_bottom_left' => array( 0 => 'post_meta' ),
	'posts_index_item_elements_bottom_right' => array(),
	'woocommerce_index_posts_per_page' => '12',
	'woocommerce_index_grid_columns' => '3-3-2',
	'woocommerce_ajax_more' => 1,
	'woocommerce_ajax_filter' => 1,
	'woocommerce_products_grid_rows_gutter' => '1em',
	'woocommerce_products_grid_rows_gutter__tablet' => '',
	'woocommerce_products_grid_rows_gutter__mobile' => '',
	'woocommerce_products_grid_columns_gutter' => '1em',
	'woocommerce_products_grid_columns_gutter__mobile' => '',
	'woocommerce_index_thumb_height' => '132%',
	'woocommerce_cart_layout' => '2-columns',
	'woocommerce_cart_width' => '1170px',
	'woocommerce_cart_cross_sells_grid_columns' => '3-3-2',
	'woocommerce_checkout_layout' => '2-columns',
	'woocommerce_checkout_width' => '960px',
	'woocommerce_sale_badge_bg_color' => '#ed6868',
	'woocommerce_sale_badge_text_color' => '#f2f2f2',
	'woocommerce_sale_badge_border_color' => 'rgba(204,204,204,0)',
	'woocommerce_review_star_color' => '#ffc34c',
	'woocommerce_alt_button_bg_color' => '',
);

$predefined['color_palette_1']                        = $colors['heading'];
$predefined['color_palette_2']                        = $colors['text'];
$predefined['color_palette_3']                        = $colors['accent'];
$predefined['color_palette_4']                        = $colors['accent2'];
$predefined['color_palette_5']                        = $colors['border'];
$predefined['color_palette_6']                        = $colors['subtitle'];
$predefined['color_palette_7']                        = $colors['white'];
$predefined['color_palette_8']                        = $colors['black'];



return $predefined;
